version: "3.9"
services:
  webhook:
    build:
      context: ./webhook
    ports:
      - "9000:9000"
    volumes:
      - "./data:/var/lib/webhook-data"
  test-client:
    build:
      context: ./test